### ISSUE TITLE
Crash when loading vi_sensor enabled models

### ISSUE THREAD

**Issue by andre-nguyen** [ethz-asl/rotors_simulator#296]
Is anyone else getting a crash when loading one of the vi_sensor configs? This is what I get when I try to launch `mav_hovering_example_with_vi_sensor.launch`

```
[ERROR] [1467682322.617647583]: link 'firefly/vi_sensor/vi_sensor_link' is not unique.
[INFO] [WallTime: 1467682323.192137] [0.000000] Calling service /gazebo/spawn_urdf_model
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/joint_state_publisher/joint_state_publisher", line 347, in <module>
    jsp.loop()
  File "/opt/ros/indigo/lib/joint_state_publisher/joint_state_publisher", line 205, in loop
    msg.position[i] = joint['position'] * factor + offset
IndexError: list assignment index out of range
Error:   link 'firefly/vi_sensor/vi_sensor_link' is not unique.
         at line 135 in /build/buildd/urdfdom-0.2.10+dfsg/urdf_parser/src/model.cpp
Error [parser_urdf.cc:2608] Unable to call parseURDF on robot model
Error [parser.cc:299] parse as old deprecated model file failed.
Error [World.cc:1527] Unable to read sdf string[...]
```

Looking at the sdf string generated by xacro (I replaced it by "..." in the above crash log), I can indeed see that two vi-sensors are being loaded but I don't understand the cause of it.

**Comment by andre-nguyen** [comment]
nvm im dumb
