### ISSUE TITLE
Catkin Build Error [mavlink]

### ISSUE THREAD

**Issue by aka-LJ** [ethz-asl/rotors_simulator#458]
Hi,

I am on Ubuntu 16.04 with ROS Kinetic, I got the error message after the catkin build step.
any ideas? 

lj@Ubuntu:~/catkin_ws/src$ cd ~/catkin_ws/
lj@Ubuntu:~/catkin_ws$ catkin build
-------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/kinetic
Workspace:                   /home/lj/catkin_ws
-------------------------------------------------------
Source Space:       [exists] /home/lj/catkin_ws/src
Log Space:         [missing] /home/lj/catkin_ws/logs
Build Space:        [exists] /home/lj/catkin_ws/build
Devel Space:        [exists] /home/lj/catkin_ws/devel
Install Space:      [unused] /home/lj/catkin_ws/install
DESTDIR:            [unused] None
-------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
-------------------------------------------------------
[build] Found '19' packages in 0.0 seconds.                                                                                                                          
[build] Updating package table.                                                                                                                                      
Starting  >>> catkin_tools_prebuild                                                                                                                                  
Finished  <<< catkin_tools_prebuild                [ 1.8 seconds ]                                                                                                   
Starting  >>> mav_msgs                                                                                                                                               
Starting  >>> mavlink                                                                                                                                                
Starting  >>> mavros_msgs                                                                                                                                            
Starting  >>> rotors_comm                                                                                                                                            
Starting  >>> rotors_description                                                                                                                                     
Starting  >>> rotors_evaluation                                                                                                                                      
_____________________________________________________________________________________________________________________________________________________________________
Errors     << mavlink:make /home/lj/catkin_ws/logs/mavlink/build.make.000.log                                                                                        
Traceback (most recent call last):
  File "/home/lj/catkin_ws/src/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
    from pymavlink.generator import mavgen
  File "/home/lj/catkin_ws/src/mavlink/pymavlink/generator/mavgen.py", line 12, in <module>
    from future import standard_library
ImportError: No module named future
Traceback (most recent call last):
  File "/home/lj/catkin_ws/src/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
    from pymavlink.generator import mavgen
  File "/home/lj/catkin_ws/src/mavlink/pymavlink/generator/mavgen.py", line 12, in <module>
    from future import standard_library
ImportError: No module named future
make[2]: *** [include/v1.0/standard/standard.h] Error 1
make[1]: *** [CMakeFiles/standard.xml-v1.0.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [include/v1.0/ardupilotmega/ardupilotmega.h] Error 1
Traceback (most recent call last):
  File "/home/lj/catkin_ws/src/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
    from pymavlink.generator import mavgen
  File "/home/lj/catkin_ws/src/mavlink/pymavlink/generator/mavgen.py", line 12, in <module>
    from future import standard_library
ImportError: No module named future
make[1]: *** [CMakeFiles/ardupilotmega.xml-v1.0.dir/all] Error 2
make[2]: *** [include/v1.0/uAvionix/uAvionix.h] Error 1
make[1]: *** [CMakeFiles/uAvionix.xml-v1.0.dir/all] Error 2
make: *** [all] Error 2
cd /home/lj/catkin_ws/build/mavlink; catkin build --get-env mavlink | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.....................................................................................................................................................................
Failed     << mavlink:make                         [ Exited with code 2 ]                                                                                            
Failed    <<< mavlink                              [ 0.2 seconds ]                                                                                                   
Abandoned <<< libmavconn                           [ Unrelated job failed ]                                                                                          
Abandoned <<< mavros                               [ Unrelated job failed ]                                                                                          
Abandoned <<< mavros_extras                        [ Unrelated job failed ]                                                                                          
Abandoned <<< planning_msgs                        [ Unrelated job failed ]                                                                                          
Abandoned <<< rotors_control                       [ Unrelated job failed ]                                                                                          
Abandoned <<< rotors_gazebo_plugins                [ Unrelated job failed ]                                                                                          
Abandoned <<< rotors_gazebo                        [ Unrelated job failed ]                                                                                          
Abandoned <<< rotors_hil_interface                 [ Unrelated job failed ]                                                                                          
Abandoned <<< rotors_joy_interface                 [ Unrelated job failed ]                                                                                          
Abandoned <<< rqt_rotors                           [ Unrelated job failed ]                                                                                          
Abandoned <<< test_mavros                          [ Unrelated job failed ]                                                                                          
Finished  <<< rotors_description                   [ 2.3 seconds ]                                                                                                   
Finished  <<< rotors_evaluation                    [ 2.5 seconds ]                                                                                                   
_____________________________________________________________________________________________________________________________________________________________________
Warnings   << mav_msgs:cmake /home/lj/catkin_ws/logs/mav_msgs/build.cmake.000.log                                                                                    
CMake Warning at /opt/ros/kinetic/share/cmake_modules/cmake/Modules/FindEigen.cmake:62 (message):
  The FindEigen.cmake Module in the cmake_modules package is deprecated.

  Please use the FindEigen3.cmake Module provided with Eigen.  Change
  instances of find_package(Eigen) to find_package(Eigen3).  Check the
  FindEigen3.cmake Module for the resulting CMake variable names.

Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)

cd /home/lj/catkin_ws/build/mav_msgs; catkin build --get-env mav_msgs | catkin env -si  /usr/bin/cmake /home/lj/catkin_ws/src/mav_comm/mav_msgs --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/lj/catkin_ws/devel/.private/mav_msgs -DCMAKE_INSTALL_PREFIX=/home/lj/catkin_ws/install; cd -
.....................................................................................................................................................................
Finished  <<< rotors_comm                          [ 4.1 seconds ]                                                                                                   
Finished  <<< mav_msgs                             [ 5.3 seconds ]                                                                                                   
Finished  <<< mavros_msgs                          [ 10.2 seconds ]                                                                                                  
[build] Summary: 6 of 18 packages succeeded.                                                                                                                         
[build]   Ignored:   2 packages were skipped or are blacklisted.                                                                                                     
[build]   Warnings:  1 packages succeeded with warnings.                                                                                                             
[build]   Abandoned: 11 packages were abandoned.                                                                                                                     
[build]   Failed:    1 packages failed.                                                                                                                              
[build] Runtime: 12.1 seconds total.                                                                                                                                 
[build] Note: Workspace packages have changed, please re-source setup files to use them.
lj@Ubuntu:~/catkin_ws$ patrik@patrik-Inspiron-1564:~/catkin_ws$ catkin build rotors_gazebo
bash: patrik@patrik-Inspiron-1564:~/catkin_ws$: No such file or directory
ped or are blacklisted.                  lj@Ubuntu:~/catkin_ws$ -----------------------------------------------------------
-----------------------------------------------------------: command not found
lj@Ubuntu:~/catkin_ws$ Profile:                     default
Profile:: command not found
lj@Ubuntu:~/catkin_ws$ Extending:        [explicit] /opt/ros/indigo
Extending:: command not found
lj@Ubuntu:~/catkin_ws$ Workspace:                   /home/patrik/catkin_ws
Workspace:: command not found
lj@Ubuntu:~/catkin_ws$ -----------------------------------------------------------
-----------------------------------------------------------: command not found
lj@Ubuntu:~/catkin_ws$ Source Space:       [exists] /home/patrik/catkin_ws/src
No command 'Source' found, did you mean:
 Command 'gource' from package 'gource' (universe)
Source: command not found
lj@Ubuntu:~/catkin_ws$ Log Space:         [missing] /home/patrik/catkin_ws/logs
No command 'Log' found, did you mean:
 Command 'iog' from package 'iog' (universe)
 Command 'mog' from package 'mazeofgalious' (universe)
 Command 'eog' from package 'eog' (main)
 Command 'dog' from package 'sheepdog' (universe)
 Command 'fog' from package 'ruby-fog' (universe)
Log: command not found
lj@Ubuntu:~/catkin_ws$ Build Space:        [exists] /home/patrik/catkin_ws/build
No command 'Build' found, did you mean:
 Command 'guild' from package 'guile-2.0-dev' (main)
Build: command not found
lj@Ubuntu:~/catkin_ws$ Devel Space:        [exists] /home/patrik/catkin_ws/devel
Devel: command not found
lj@Ubuntu:~/catkin_ws$ Install Space:      [unused] /home/patrik/catkin_ws/install
No command 'Install' found, did you mean:
 Command 'install' from package 'coreutils' (main)
Install: command not found
lj@Ubuntu:~/catkin_ws$ DESTDIR:            [unused] None
 DESTDIR:: command not found
lj@Ubuntu:~/catkin_ws$ -----------------------------------------------------------
-----------------------------------------------------------: command not found
lj@Ubuntu:~/catkin_ws$ Devel Space Layout:          merged
Devel: command not found
lj@Ubuntu:~/catkin_ws$ Install Space Layout:        None
No command 'Install' found, did you mean:
 Command 'install' from package 'coreutils' (main)
Install: command not found
lj@Ubuntu:~/catkin_ws$ -----------------------------------------------------------
-----------------------------------------------------------: command not found
lj@Ubuntu:~/catkin_ws$ Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional: command not found
lj@Ubuntu:~/catkin_ws$ Additional Make Args:        None
Additional: command not found
lj@Ubuntu:~/catkin_ws$ Additional catkin Make Args: None
Additional: command not found
lj@Ubuntu:~/catkin_ws$ Internal Make Job Server:    True
Internal: command not found
lj@Ubuntu:~/catkin_ws$ Cache Job Environments:      False
Cache: command not found
lj@Ubuntu:~/catkin_ws$ -----------------------------------------------------------
-----------------------------------------------------------: command not found
lj@Ubuntu:~/catkin_ws$ Whitelisted Packages:        None
Whitelisted: command not found
lj@Ubuntu:~/catkin_ws$ Blacklisted Packages:        None
Blacklisted: command not found
lj@Ubuntu:~/catkin_ws$ -----------------------------------------------------------
-----------------------------------------------------------: command not found
lj@Ubuntu:~/catkin_ws$ Workspace configuration appears valid.
Workspace: command not found
lj@Ubuntu:~/catkin_ws$ 
lj@Ubuntu:~/catkin_ws$ NOTE: Forcing CMake to run for each package.
NOTE:: command not found
lj@Ubuntu:~/catkin_ws$ -----------------------------------------------------------
-----------------------------------------------------------: command not found
lj@Ubuntu:~/catkin_ws$ [build] Found '45' packages in 0.0 seconds.                                                                                                      
[build]: command not found
lj@Ubuntu:~/catkin_ws$ [build] Updating package table.                                                                                                                  
[build]: command not found
lj@Ubuntu:~/catkin_ws$ Starting  >>> mav_msgs                                                                                                                           
bash: syntax error near unexpected token `>'
lj@Ubuntu:~/catkin_ws$ Starting  >>> rotors_comm                                                                                                                        
bash: syntax error near unexpected token `>'
lj@Ubuntu:~/catkin_ws$ Finished  <<< rotors_comm                          [ 4.3 seconds ]                                                                               
Finished: command not found
lj@Ubuntu:~/catkin_ws$ Finished  <<< mav_msgs                             [ 5.3 seconds ]                                                                               
Finished: command not found
lj@Ubuntu:~/catkin_ws$ Starting  >>> rotors_control                                                                                                                     
bash: syntax error near unexpected token `>'
lj@Ubuntu:~/catkin_ws$ Finished  <<< rotors_control                       [ 25.0 seconds ]                                                                              
Finished: command not found
lj@Ubuntu:~/catkin_ws$ Starting  >>> rotors_gazebo_plugins                                                                                                              
bash: syntax error near unexpected token `>'
lj@Ubuntu:~/catkin_ws$ _________________________________________________________________________________________________________________________________________________
_________________________________________________________________________________________________________________________________________________: command not found
lj@Ubuntu:~/catkin_ws$ Errors     << rotors_gazebo_plugins:make /home/patrik/catkin_ws/logs/rotors_gazebo_plugins/build.make.000.log                                    
> make[2]: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: Command not found
> make[2]: *** [Wrench.pb.cc] Error 127
> make[1]: *** [CMakeFiles/mav_msgs.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> make: *** [all] Error 2
> cd /home/patrik/catkin_ws/build/rotors_gazebo_plugins; catkin build --get-env rotors_gazebo_plugins | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
> .................................................................................................................................................
> Failed     << rotors_gazebo_plugins:make           [ Exited with code 2 ]                                                                        
> Failed    <<< rotors_gazebo_plugins                [ 4.2 seconds ]                                                                               
> Abandoned <<< rotors_gazebo                        [ Unrelated job failed ]                                                                      
> [build] Summary: 3 of 5 packages succeeded.                                                                                                      
> [build]   Ignored:   40 packages were skipped or are blacklisted.                                                                                
> [build]   Warnings:  None.                                                                                                                       
> [build]   Abandoned: 1 packages were abandoned.                                                                                                  
> [build]   Failed:    1 packages failed.                                                                                                          
> [build] Runtime: 34.7 seconds total.                                                                                                             
> [build] Note: Workspace packages have changed, please re-source setup files to use them.^C

**Comment by helenol** [comment]
Resolution from here: https://github.com/ArduPilot/pymavlink/issues/25

```
pip install future
```

And if you don't have pip...
https://pip.pypa.io/en/stable/installing/

Hope this helps!

**Comment by aka-LJ** [comment]
It worked, thank you.

**Comment by Hjayant** [comment]
Hi ,
I am having catkin build problem.And I am using ubuntu16.04 and ros kinetic. Any idea??
![screenshot from 2018-12-05 05-25-49](https://user-images.githubusercontent.com/37120263/49464495-05d11d80-f821-11e8-9e18-2b5816132340.png)
![screenshot from 2018-12-05 05-25-58](https://user-images.githubusercontent.com/37120263/49464496-0669b400-f821-11e8-9e49-3fb52598c083.png)
![screenshot from 2018-12-05 05-26-08](https://user-images.githubusercontent.com/37120263/49464497-0669b400-f821-11e8-977d-5f8e59634e2e.png)
![screenshot from 2018-12-05 05-26-20](https://user-images.githubusercontent.com/37120263/49464500-0669b400-f821-11e8-9943-0100074b9882.png)

**Comment by pinkneonsign** [comment]
https://github.com/ArduPilot/pymavlink/issues/25#issuecomment-483651986
